# Generated by Django 2.1.4 on 2018-12-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cache',
            fields=[
                ('path', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('vector', models.BinaryField()),
                ('color', models.BinaryField()),
                ('shape', models.BinaryField()),
                ('texture', models.BinaryField()),
                ('cnn', models.BinaryField()),
            ],
        ),
    ]
